// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(tenex_orchestratorFFI)
import tenex_orchestratorFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_tenex_orchestrator_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_tenex_orchestrator_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureTenexOrchestratorInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Core orchestrator object exposed via UniFFI.
 * Manages all TENEX system services and configuration.
 */
public protocol OrchestratorCoreProtocol: AnyObject, Sendable {
    
    /**
     * Add a key to an existing provider. Creates the provider if it doesn't exist.
     */
    func addProviderKey(providerId: String, apiKey: String) throws 
    
    /**
     * Auto-connect detected providers. Returns true if any were added.
     */
    func autoConnectProviders() throws  -> Bool
    
    /**
     * Check if config file exists.
     */
    func configExists()  -> Bool
    
    /**
     * Connect a provider with the given API key/credential.
     */
    func connectProvider(providerId: String, apiKey: String) throws 
    
    /**
     * Get recent daemon logs.
     */
    func daemonLogs()  -> [String]
    
    /**
     * Detect OpenClaw installation. Returns JSON with credentials if found, or empty string.
     */
    func detectOpenclaw()  -> String
    
    /**
     * Detect all providers and return their status.
     */
    func detectProviders()  -> [ProviderInfo]
    
    /**
     * Disconnect a provider.
     */
    func disconnectProvider(providerId: String) throws 
    
    /**
     * Fetch available models from a provider (Ollama or OpenRouter).
     */
    func fetchModels(providerId: String) throws  -> [String]
    
    /**
     * Import OpenClaw credentials into providers config.
     */
    func importOpenclawCredentials() throws  -> Bool
    
    /**
     * Initialize the orchestrator: load config, configure services from stored settings.
     */
    func `init`() throws 
    
    /**
     * Check if LLMs file exists.
     */
    func llmsExist()  -> Bool
    
    /**
     * Load all config as a JSON string.
     */
    func loadConfigJson()  -> String
    
    /**
     * Load embed config as a JSON string.
     */
    func loadEmbedJson()  -> String
    
    /**
     * Load image config as a JSON string.
     */
    func loadImageJson()  -> String
    
    /**
     * Load launcher config as a JSON string.
     */
    func loadLauncherJson()  -> String
    
    /**
     * Load LLMs as a JSON string.
     */
    func loadLlmsJson()  -> String
    
    /**
     * Load providers as a JSON string.
     */
    func loadProvidersJson()  -> String
    
    /**
     * Run config migration (launcher fields from config.json → launcher.json).
     */
    func migrateConfig() 
    
    /**
     * Check if onboarding is needed.
     */
    func needsOnboarding()  -> Bool
    
    /**
     * Get recent ngrok logs.
     */
    func ngrokLogs()  -> [String]
    
    /**
     * Go back to the previous onboarding step.
     */
    func onboardingBack() 
    
    /**
     * Check if onboarding is complete.
     */
    func onboardingIsComplete()  -> Bool
    
    /**
     * Advance to the next onboarding step.
     */
    func onboardingNext() 
    
    /**
     * Get the current onboarding step.
     */
    func onboardingStep()  -> FfiOnboardingStep
    
    /**
     * Check if providers file exists.
     */
    func providersExist()  -> Bool
    
    /**
     * Get recent relay logs.
     */
    func relayLogs()  -> [String]
    
    /**
     * Remove a key from a provider by index.
     */
    func removeProviderKey(providerId: String, index: UInt32) throws 
    
    /**
     * Reorder a key within a provider's key list.
     */
    func reorderProviderKey(providerId: String, fromIndex: UInt32, toIndex: UInt32) throws 
    
    /**
     * Save config from a JSON string.
     */
    func saveConfigJson(json: String) throws 
    
    /**
     * Save embed config from a JSON string.
     */
    func saveEmbedJson(json: String) throws 
    
    /**
     * Save image config from a JSON string.
     */
    func saveImageJson(json: String) throws 
    
    /**
     * Save launcher config from a JSON string.
     */
    func saveLauncherJson(json: String) throws 
    
    /**
     * Save LLMs from a JSON string.
     */
    func saveLlmsJson(json: String) throws 
    
    /**
     * Save relay configuration from onboarding.
     * `mode` should be "remote" or "local".
     */
    func saveOnboardingRelay(mode: String, remoteUrl: String, ngrokEnabled: Bool) throws 
    
    /**
     * Save providers from a JSON string.
     */
    func saveProvidersJson(json: String) throws 
    
    /**
     * Seed default LLM configurations based on connected providers.
     * Returns true if any configs were added.
     */
    func seedDefaultLlms() throws  -> Bool
    
    /**
     * Get a snapshot of all service statuses.
     */
    func serviceStatus()  -> ServiceStatusSnapshot
    
    /**
     * Shut down all managed services.
     */
    func shutdown() throws 
    
    /**
     * Start the daemon.
     */
    func startDaemon() throws 
    
    /**
     * Start ngrok.
     */
    func startNgrok() throws 
    
    /**
     * Start the relay.
     */
    func startRelay() throws 
    
    /**
     * Stop the daemon.
     */
    func stopDaemon() throws 
    
    /**
     * Stop ngrok.
     */
    func stopNgrok() throws 
    
    /**
     * Stop the relay.
     */
    func stopRelay() throws 
    
}
/**
 * Core orchestrator object exposed via UniFFI.
 * Manages all TENEX system services and configuration.
 */
open class OrchestratorCore: OrchestratorCoreProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_tenex_orchestrator_fn_clone_orchestratorcore(self.pointer, $0) }
    }
    /**
     * Create a new OrchestratorCore instance.
     * `repo_root` is the path to the TENEX repository root (for dev binary resolution).
     * Pass `None` in production when binaries are bundled.
     */
public convenience init(repoRoot: String?) {
    let pointer =
        try! rustCall() {
    uniffi_tenex_orchestrator_fn_constructor_orchestratorcore_new(
        FfiConverterOptionString.lower(repoRoot),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_tenex_orchestrator_fn_free_orchestratorcore(pointer, $0) }
    }

    

    
    /**
     * Add a key to an existing provider. Creates the provider if it doesn't exist.
     */
open func addProviderKey(providerId: String, apiKey: String)throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_add_provider_key(self.uniffiClonePointer(),
        FfiConverterString.lower(providerId),
        FfiConverterString.lower(apiKey),$0
    )
}
}
    
    /**
     * Auto-connect detected providers. Returns true if any were added.
     */
open func autoConnectProviders()throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_auto_connect_providers(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Check if config file exists.
     */
open func configExists() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_config_exists(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Connect a provider with the given API key/credential.
     */
open func connectProvider(providerId: String, apiKey: String)throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_connect_provider(self.uniffiClonePointer(),
        FfiConverterString.lower(providerId),
        FfiConverterString.lower(apiKey),$0
    )
}
}
    
    /**
     * Get recent daemon logs.
     */
open func daemonLogs() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_daemon_logs(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Detect OpenClaw installation. Returns JSON with credentials if found, or empty string.
     */
open func detectOpenclaw() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_detect_openclaw(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Detect all providers and return their status.
     */
open func detectProviders() -> [ProviderInfo]  {
    return try!  FfiConverterSequenceTypeProviderInfo.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_detect_providers(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Disconnect a provider.
     */
open func disconnectProvider(providerId: String)throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_disconnect_provider(self.uniffiClonePointer(),
        FfiConverterString.lower(providerId),$0
    )
}
}
    
    /**
     * Fetch available models from a provider (Ollama or OpenRouter).
     */
open func fetchModels(providerId: String)throws  -> [String]  {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_fetch_models(self.uniffiClonePointer(),
        FfiConverterString.lower(providerId),$0
    )
})
}
    
    /**
     * Import OpenClaw credentials into providers config.
     */
open func importOpenclawCredentials()throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_import_openclaw_credentials(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Initialize the orchestrator: load config, configure services from stored settings.
     */
open func `init`()throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_init(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Check if LLMs file exists.
     */
open func llmsExist() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_llms_exist(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Load all config as a JSON string.
     */
open func loadConfigJson() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_load_config_json(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Load embed config as a JSON string.
     */
open func loadEmbedJson() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_load_embed_json(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Load image config as a JSON string.
     */
open func loadImageJson() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_load_image_json(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Load launcher config as a JSON string.
     */
open func loadLauncherJson() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_load_launcher_json(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Load LLMs as a JSON string.
     */
open func loadLlmsJson() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_load_llms_json(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Load providers as a JSON string.
     */
open func loadProvidersJson() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_load_providers_json(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Run config migration (launcher fields from config.json → launcher.json).
     */
open func migrateConfig()  {try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_migrate_config(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Check if onboarding is needed.
     */
open func needsOnboarding() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_needs_onboarding(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get recent ngrok logs.
     */
open func ngrokLogs() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_ngrok_logs(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Go back to the previous onboarding step.
     */
open func onboardingBack()  {try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_onboarding_back(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Check if onboarding is complete.
     */
open func onboardingIsComplete() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_onboarding_is_complete(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Advance to the next onboarding step.
     */
open func onboardingNext()  {try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_onboarding_next(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Get the current onboarding step.
     */
open func onboardingStep() -> FfiOnboardingStep  {
    return try!  FfiConverterTypeFfiOnboardingStep_lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_onboarding_step(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Check if providers file exists.
     */
open func providersExist() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_providers_exist(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get recent relay logs.
     */
open func relayLogs() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_relay_logs(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Remove a key from a provider by index.
     */
open func removeProviderKey(providerId: String, index: UInt32)throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_remove_provider_key(self.uniffiClonePointer(),
        FfiConverterString.lower(providerId),
        FfiConverterUInt32.lower(index),$0
    )
}
}
    
    /**
     * Reorder a key within a provider's key list.
     */
open func reorderProviderKey(providerId: String, fromIndex: UInt32, toIndex: UInt32)throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_reorder_provider_key(self.uniffiClonePointer(),
        FfiConverterString.lower(providerId),
        FfiConverterUInt32.lower(fromIndex),
        FfiConverterUInt32.lower(toIndex),$0
    )
}
}
    
    /**
     * Save config from a JSON string.
     */
open func saveConfigJson(json: String)throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_save_config_json(self.uniffiClonePointer(),
        FfiConverterString.lower(json),$0
    )
}
}
    
    /**
     * Save embed config from a JSON string.
     */
open func saveEmbedJson(json: String)throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_save_embed_json(self.uniffiClonePointer(),
        FfiConverterString.lower(json),$0
    )
}
}
    
    /**
     * Save image config from a JSON string.
     */
open func saveImageJson(json: String)throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_save_image_json(self.uniffiClonePointer(),
        FfiConverterString.lower(json),$0
    )
}
}
    
    /**
     * Save launcher config from a JSON string.
     */
open func saveLauncherJson(json: String)throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_save_launcher_json(self.uniffiClonePointer(),
        FfiConverterString.lower(json),$0
    )
}
}
    
    /**
     * Save LLMs from a JSON string.
     */
open func saveLlmsJson(json: String)throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_save_llms_json(self.uniffiClonePointer(),
        FfiConverterString.lower(json),$0
    )
}
}
    
    /**
     * Save relay configuration from onboarding.
     * `mode` should be "remote" or "local".
     */
open func saveOnboardingRelay(mode: String, remoteUrl: String, ngrokEnabled: Bool)throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_save_onboarding_relay(self.uniffiClonePointer(),
        FfiConverterString.lower(mode),
        FfiConverterString.lower(remoteUrl),
        FfiConverterBool.lower(ngrokEnabled),$0
    )
}
}
    
    /**
     * Save providers from a JSON string.
     */
open func saveProvidersJson(json: String)throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_save_providers_json(self.uniffiClonePointer(),
        FfiConverterString.lower(json),$0
    )
}
}
    
    /**
     * Seed default LLM configurations based on connected providers.
     * Returns true if any configs were added.
     */
open func seedDefaultLlms()throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_seed_default_llms(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get a snapshot of all service statuses.
     */
open func serviceStatus() -> ServiceStatusSnapshot  {
    return try!  FfiConverterTypeServiceStatusSnapshot_lift(try! rustCall() {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_service_status(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Shut down all managed services.
     */
open func shutdown()throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_shutdown(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Start the daemon.
     */
open func startDaemon()throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_start_daemon(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Start ngrok.
     */
open func startNgrok()throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_start_ngrok(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Start the relay.
     */
open func startRelay()throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_start_relay(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Stop the daemon.
     */
open func stopDaemon()throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_stop_daemon(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Stop ngrok.
     */
open func stopNgrok()throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_stop_ngrok(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Stop the relay.
     */
open func stopRelay()throws   {try rustCallWithError(FfiConverterTypeOrchestratorError_lift) {
    uniffi_tenex_orchestrator_fn_method_orchestratorcore_stop_relay(self.uniffiClonePointer(),$0
    )
}
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOrchestratorCore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = OrchestratorCore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> OrchestratorCore {
        return OrchestratorCore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: OrchestratorCore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OrchestratorCore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: OrchestratorCore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOrchestratorCore_lift(_ pointer: UnsafeMutableRawPointer) throws -> OrchestratorCore {
    return try FfiConverterTypeOrchestratorCore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOrchestratorCore_lower(_ value: OrchestratorCore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeOrchestratorCore.lower(value)
}




/**
 * Information about a detected provider.
 */
public struct ProviderInfo {
    public var id: String
    public var displayName: String
    public var available: Bool
    public var connected: Bool
    public var subtitle: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, displayName: String, available: Bool, connected: Bool, subtitle: String) {
        self.id = id
        self.displayName = displayName
        self.available = available
        self.connected = connected
        self.subtitle = subtitle
    }
}

#if compiler(>=6)
extension ProviderInfo: Sendable {}
#endif


extension ProviderInfo: Equatable, Hashable {
    public static func ==(lhs: ProviderInfo, rhs: ProviderInfo) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.displayName != rhs.displayName {
            return false
        }
        if lhs.available != rhs.available {
            return false
        }
        if lhs.connected != rhs.connected {
            return false
        }
        if lhs.subtitle != rhs.subtitle {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(displayName)
        hasher.combine(available)
        hasher.combine(connected)
        hasher.combine(subtitle)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProviderInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProviderInfo {
        return
            try ProviderInfo(
                id: FfiConverterString.read(from: &buf), 
                displayName: FfiConverterString.read(from: &buf), 
                available: FfiConverterBool.read(from: &buf), 
                connected: FfiConverterBool.read(from: &buf), 
                subtitle: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ProviderInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
        FfiConverterBool.write(value.available, into: &buf)
        FfiConverterBool.write(value.connected, into: &buf)
        FfiConverterString.write(value.subtitle, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProviderInfo_lift(_ buf: RustBuffer) throws -> ProviderInfo {
    return try FfiConverterTypeProviderInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProviderInfo_lower(_ value: ProviderInfo) -> RustBuffer {
    return FfiConverterTypeProviderInfo.lower(value)
}


/**
 * Status snapshot of all three services.
 */
public struct ServiceStatusSnapshot {
    public var daemonStatus: FfiProcessStatus
    public var daemonError: String?
    public var relayStatus: FfiProcessStatus
    public var relayError: String?
    public var ngrokStatus: FfiProcessStatus
    public var ngrokError: String?
    public var ngrokTunnelUrl: String?
    public var relayUrl: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(daemonStatus: FfiProcessStatus, daemonError: String?, relayStatus: FfiProcessStatus, relayError: String?, ngrokStatus: FfiProcessStatus, ngrokError: String?, ngrokTunnelUrl: String?, relayUrl: String?) {
        self.daemonStatus = daemonStatus
        self.daemonError = daemonError
        self.relayStatus = relayStatus
        self.relayError = relayError
        self.ngrokStatus = ngrokStatus
        self.ngrokError = ngrokError
        self.ngrokTunnelUrl = ngrokTunnelUrl
        self.relayUrl = relayUrl
    }
}

#if compiler(>=6)
extension ServiceStatusSnapshot: Sendable {}
#endif


extension ServiceStatusSnapshot: Equatable, Hashable {
    public static func ==(lhs: ServiceStatusSnapshot, rhs: ServiceStatusSnapshot) -> Bool {
        if lhs.daemonStatus != rhs.daemonStatus {
            return false
        }
        if lhs.daemonError != rhs.daemonError {
            return false
        }
        if lhs.relayStatus != rhs.relayStatus {
            return false
        }
        if lhs.relayError != rhs.relayError {
            return false
        }
        if lhs.ngrokStatus != rhs.ngrokStatus {
            return false
        }
        if lhs.ngrokError != rhs.ngrokError {
            return false
        }
        if lhs.ngrokTunnelUrl != rhs.ngrokTunnelUrl {
            return false
        }
        if lhs.relayUrl != rhs.relayUrl {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(daemonStatus)
        hasher.combine(daemonError)
        hasher.combine(relayStatus)
        hasher.combine(relayError)
        hasher.combine(ngrokStatus)
        hasher.combine(ngrokError)
        hasher.combine(ngrokTunnelUrl)
        hasher.combine(relayUrl)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeServiceStatusSnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ServiceStatusSnapshot {
        return
            try ServiceStatusSnapshot(
                daemonStatus: FfiConverterTypeFfiProcessStatus.read(from: &buf), 
                daemonError: FfiConverterOptionString.read(from: &buf), 
                relayStatus: FfiConverterTypeFfiProcessStatus.read(from: &buf), 
                relayError: FfiConverterOptionString.read(from: &buf), 
                ngrokStatus: FfiConverterTypeFfiProcessStatus.read(from: &buf), 
                ngrokError: FfiConverterOptionString.read(from: &buf), 
                ngrokTunnelUrl: FfiConverterOptionString.read(from: &buf), 
                relayUrl: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ServiceStatusSnapshot, into buf: inout [UInt8]) {
        FfiConverterTypeFfiProcessStatus.write(value.daemonStatus, into: &buf)
        FfiConverterOptionString.write(value.daemonError, into: &buf)
        FfiConverterTypeFfiProcessStatus.write(value.relayStatus, into: &buf)
        FfiConverterOptionString.write(value.relayError, into: &buf)
        FfiConverterTypeFfiProcessStatus.write(value.ngrokStatus, into: &buf)
        FfiConverterOptionString.write(value.ngrokError, into: &buf)
        FfiConverterOptionString.write(value.ngrokTunnelUrl, into: &buf)
        FfiConverterOptionString.write(value.relayUrl, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeServiceStatusSnapshot_lift(_ buf: RustBuffer) throws -> ServiceStatusSnapshot {
    return try FfiConverterTypeServiceStatusSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeServiceStatusSnapshot_lower(_ value: ServiceStatusSnapshot) -> RustBuffer {
    return FfiConverterTypeServiceStatusSnapshot.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Onboarding step as a simple string for FFI.
 */

public enum FfiOnboardingStep {
    
    case identity
    case openClawImport
    case relay
    case providers
    case llMs
    case mobileSetup
}


#if compiler(>=6)
extension FfiOnboardingStep: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiOnboardingStep: FfiConverterRustBuffer {
    typealias SwiftType = FfiOnboardingStep

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiOnboardingStep {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .identity
        
        case 2: return .openClawImport
        
        case 3: return .relay
        
        case 4: return .providers
        
        case 5: return .llMs
        
        case 6: return .mobileSetup
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiOnboardingStep, into buf: inout [UInt8]) {
        switch value {
        
        
        case .identity:
            writeInt(&buf, Int32(1))
        
        
        case .openClawImport:
            writeInt(&buf, Int32(2))
        
        
        case .relay:
            writeInt(&buf, Int32(3))
        
        
        case .providers:
            writeInt(&buf, Int32(4))
        
        
        case .llMs:
            writeInt(&buf, Int32(5))
        
        
        case .mobileSetup:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiOnboardingStep_lift(_ buf: RustBuffer) throws -> FfiOnboardingStep {
    return try FfiConverterTypeFfiOnboardingStep.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiOnboardingStep_lower(_ value: FfiOnboardingStep) -> RustBuffer {
    return FfiConverterTypeFfiOnboardingStep.lower(value)
}


extension FfiOnboardingStep: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Process status as a simple string for FFI.
 */

public enum FfiProcessStatus {
    
    case stopped
    case starting
    case running
    case failed
}


#if compiler(>=6)
extension FfiProcessStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiProcessStatus: FfiConverterRustBuffer {
    typealias SwiftType = FfiProcessStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiProcessStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .stopped
        
        case 2: return .starting
        
        case 3: return .running
        
        case 4: return .failed
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiProcessStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .stopped:
            writeInt(&buf, Int32(1))
        
        
        case .starting:
            writeInt(&buf, Int32(2))
        
        
        case .running:
            writeInt(&buf, Int32(3))
        
        
        case .failed:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiProcessStatus_lift(_ buf: RustBuffer) throws -> FfiProcessStatus {
    return try FfiConverterTypeFfiProcessStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiProcessStatus_lower(_ value: FfiProcessStatus) -> RustBuffer {
    return FfiConverterTypeFfiProcessStatus.lower(value)
}


extension FfiProcessStatus: Equatable, Hashable {}







/**
 * Error type exposed via UniFFI.
 */
public enum OrchestratorError: Swift.Error {

    
    
    case General(message: String
    )
    case Config(message: String
    )
    case Process(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOrchestratorError: FfiConverterRustBuffer {
    typealias SwiftType = OrchestratorError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OrchestratorError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .General(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Config(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Process(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: OrchestratorError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .General(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Config(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Process(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOrchestratorError_lift(_ buf: RustBuffer) throws -> OrchestratorError {
    return try FfiConverterTypeOrchestratorError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOrchestratorError_lower(_ value: OrchestratorError) -> RustBuffer {
    return FfiConverterTypeOrchestratorError.lower(value)
}


extension OrchestratorError: Equatable, Hashable {}




extension OrchestratorError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeProviderInfo: FfiConverterRustBuffer {
    typealias SwiftType = [ProviderInfo]

    public static func write(_ value: [ProviderInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeProviderInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ProviderInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [ProviderInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeProviderInfo.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_tenex_orchestrator_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_add_provider_key() != 57797) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_auto_connect_providers() != 21136) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_config_exists() != 6523) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_connect_provider() != 14240) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_daemon_logs() != 27841) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_detect_openclaw() != 7507) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_detect_providers() != 56562) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_disconnect_provider() != 552) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_fetch_models() != 5573) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_import_openclaw_credentials() != 57326) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_init() != 3358) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_llms_exist() != 43030) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_load_config_json() != 42519) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_load_embed_json() != 41795) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_load_image_json() != 1287) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_load_launcher_json() != 58625) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_load_llms_json() != 42585) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_load_providers_json() != 25200) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_migrate_config() != 48304) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_needs_onboarding() != 61022) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_ngrok_logs() != 45989) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_onboarding_back() != 64762) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_onboarding_is_complete() != 61194) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_onboarding_next() != 13621) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_onboarding_step() != 27341) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_providers_exist() != 56123) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_relay_logs() != 16801) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_remove_provider_key() != 19506) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_reorder_provider_key() != 8023) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_save_config_json() != 35079) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_save_embed_json() != 8720) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_save_image_json() != 63559) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_save_launcher_json() != 30147) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_save_llms_json() != 42918) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_save_onboarding_relay() != 52376) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_save_providers_json() != 30125) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_seed_default_llms() != 10901) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_service_status() != 55086) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_shutdown() != 25992) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_start_daemon() != 54419) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_start_ngrok() != 12883) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_start_relay() != 59813) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_stop_daemon() != 38651) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_stop_ngrok() != 8265) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_method_orchestratorcore_stop_relay() != 60774) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_tenex_orchestrator_checksum_constructor_orchestratorcore_new() != 20650) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureTenexOrchestratorInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all